- name: install dispatch component
  hosts: dispatch
  become: yes
  tasks:
  - name: install golang
    ansible.buitin.yum:
      name: golang
      state: installed
  - name: check roboshop user exist or not
    ansible.builtin.command: id roboshop
    register: out
    igonore_errors: true
  - when: out.rc !=0
    name: create user roboshop
    become: yes
    ansible.builtin.user:
      name: roboshop
  - name: check app directory exist or not
    ansible.builtin.stat:
      path: /app
    register: directory
  - name: print the directory status
    ansible.builtin.debug:
      msg: "output:{{dirctory}}"
  - when: directory.stat.exist== False
    name: create /app directory
    ansible.builtin.file:
      path: /app
      state: directory
  - name: download dispatch artifact
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/dispatch.zip
      dest: /tmp
  - name: extract dispatch artifact
    ansible.builtin.unarchive:
      src: /tmp/dispatch.zip
      dest: /app
      remote_src: yes 
  - name: Initialize Go Module
    ansible.builtin.command:
      cmd: go mod init dispatch
      chdir: /app
      creates: /app/go.mod # Only runs if go.mod doesn't exist
  - name: Get Go Dependencies
    ansible.builtin.command:
      cmd: go get
      chdir: /app
  - name: Build Go Application
    ansible.builtin.command:
      cmd: go build -o dispatch
      chdir: /app
  - name: copy dispatch service
    ansible.builtin.copy:
      src: dispatch.service
      dest: /etc/systemd/system/dispatch.service
  - name: daemon reload
    ansible.builtin.systemd:
      daemon_reload: true
  - name: restart dispatch
    ansible.builtin.service:
      name: dispatch
      state: restarted
      enabled: true